// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPXtxT6w55OG8onTT6sqBZtrvs1iPSdz4',
    appId: '1:549613685702:web:633a1d1a1d43dab1fe80c7',
    messagingSenderId: '549613685702',
    projectId: 'to-do-list-bfdf4',
    authDomain: 'to-do-list-bfdf4.firebaseapp.com',
    storageBucket: 'to-do-list-bfdf4.appspot.com',
    measurementId: 'G-1G6N4QN1WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8smcdKtV1_XxncYCLdJaS6aTmp48pP6o',
    appId: '1:549613685702:android:e80e3e1ad4e5b37dfe80c7',
    messagingSenderId: '549613685702',
    projectId: 'to-do-list-bfdf4',
    storageBucket: 'to-do-list-bfdf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWcCyFPy5SRwcgEzirTtk52Nh0OfCk0NA',
    appId: '1:549613685702:ios:c3e18f56e541a9b0fe80c7',
    messagingSenderId: '549613685702',
    projectId: 'to-do-list-bfdf4',
    storageBucket: 'to-do-list-bfdf4.appspot.com',
    iosBundleId: 'com.example.baseTodolist',
  );
}
